/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EventId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Event = IDL.Record({
  'id' : EventId,
  'title' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryId = IDL.Nat;
export const GalleryImage = IDL.Record({
  'id' : GalleryId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'uploadedAt' : Timestamp,
});
export const MemberId = IDL.Nat;
export const TeamMember = IDL.Record({
  'id' : MemberId,
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'image' : ExternalBlob,
  'registrationNo' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [Event],
      [],
    ),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [GalleryImage],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [TeamMember],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEvent' : IDL.Func([EventId], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([GalleryId], [IDL.Bool], []),
  'deleteTeamMember' : IDL.Func([MemberId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
  'getTeamMember' : IDL.Func([MemberId], [IDL.Opt(TeamMember)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ContactSubmission],
      [],
    ),
  'updateEvent' : IDL.Func(
      [EventId, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [MemberId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EventId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Event = IDL.Record({
    'id' : EventId,
    'title' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryId = IDL.Nat;
  const GalleryImage = IDL.Record({
    'id' : GalleryId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'uploadedAt' : Timestamp,
  });
  const MemberId = IDL.Nat;
  const TeamMember = IDL.Record({
    'id' : MemberId,
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'image' : ExternalBlob,
    'registrationNo' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [Event],
        [],
      ),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [GalleryImage],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [TeamMember],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEvent' : IDL.Func([EventId], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([GalleryId], [IDL.Bool], []),
    'deleteTeamMember' : IDL.Func([MemberId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
    'getTeamMember' : IDL.Func([MemberId], [IDL.Opt(TeamMember)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContactSubmission],
        [],
      ),
    'updateEvent' : IDL.Func(
        [EventId, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [MemberId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };