/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactId = bigint;
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface Event {
  'id' : EventId,
  'title' : string,
  'date' : Timestamp,
  'description' : string,
  'imageUrl' : string,
  'location' : string,
}
export type EventId = bigint;
export type ExternalBlob = Uint8Array;
export type GalleryId = bigint;
export interface GalleryImage {
  'id' : GalleryId,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
  'uploadedAt' : Timestamp,
}
export type MemberId = bigint;
export interface TeamMember {
  'id' : MemberId,
  'branch' : string,
  'name' : string,
  'role' : string,
  'image' : ExternalBlob,
  'registrationNo' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addEvent' : ActorMethod<[string, string, bigint, string, string], Event>,
  'addGalleryImage' : ActorMethod<[string, string, ExternalBlob], GalleryImage>,
  'addTeamMember' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    TeamMember
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEvent' : ActorMethod<[EventId], boolean>,
  'deleteGalleryImage' : ActorMethod<[GalleryId], boolean>,
  'deleteTeamMember' : ActorMethod<[MemberId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  'getTeamMember' : ActorMethod<[MemberId], [] | [TeamMember]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'submitContactForm' : ActorMethod<
    [string, string, string],
    ContactSubmission
  >,
  'updateEvent' : ActorMethod<
    [EventId, string, string, bigint, string, string],
    boolean
  >,
  'updateTeamMember' : ActorMethod<
    [MemberId, string, string, string, string, ExternalBlob],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];